### ISSUE TITLE
Broken link to "neue statistik" when not in VPN

### ISSUE THREAD

**Issue by janheinrichmerker** [webis-de/webis-de.github.io#10]
The "neue statistik" link to https://files.webis.de/software/internal/curriculum-neue-statistik/content/start.html is broken:
https://github.com/webis-de/webis-de.github.io/blob/79c667b750eeef6b534939523bd34a6ecf2fb545/facilities.html#L404
The linked web page reports "403 Forbidden" when not connected via VPN.

**Comment by johanneskiesel** [comment]
Unfortunately, we are not allowed to serve the material outside the VPN. Working as intented ;)
