### ISSUE TITLE
Halle → Jena: domain and links

### ISSUE THREAD

**Issue by janheinrichmerker** [webis-de/webis-de.github.io#19]
Currently, most of the links are mapped to the Jena [homepage](https://jena.webis.de).
Where appropriate, deep links should be added.

- [x] Webis subdomain
    https://hannover.webis.de → https://fmi.uni-jena.de/institut-fuer-informatik/datenbanken-und-informationssysteme
- [ ] Deep-link chair/home
- [ ] Deep-link people
    - [ ] individual group members
- [ ] Deep-link teaching
- [ ] Deep-link research
- [ ] Update content on https://webis.de
    - [ ] affiliations
    - [ ] links
- [ ] Update content on https://touche.webis.de
    - [ ] affiliations
    - [ ] links
- [ ] Update `webis-people.bib`

**Comment by johanneskiesel** [comment]
I think this is obsolete with the usage of webis-people.bib. Only thing that might be missing are the links from research pages to appropriate person urls, but this will be resolved as soon as research pages are generated automatically (some point next year).
