### ISSUE TITLE
Groningen website

### ISSUE THREAD

**Issue by janheinrichmerker** [webis-de/webis-de.github.io#21]
Currently, most of the links are mapped to the Groningen [homepage](https://groningen.webis.de).
Where appropriate, deep links should be added.

- [x] Add Webis subdomain
    https://groningen.webis.de → ?
    (I'd suggest a temp redirect to https://rug.nl/staff/khalid.alkhatib until a dedicated website is available)
- [ ] Deep-link chair/home
- [ ] Deep-link people
    - [ ] individual group members
- [ ] Deep-link teaching
- [ ] Deep-link research
- [ ] Update content on https://webis.de
    - [ ] affiliations
    - [ ] links
- [ ] Update `webis-people.bib`

**Comment by johanneskiesel** [comment]
Can be re-opened once Groningen pages exist
