### ISSUE TITLE
Consistent university names

### ISSUE THREAD

**Issue by janheinrichmerker** [webis-de/webis-de.github.io#22]
Trying to use more official names for the affiliations on the websites.
Here's my rule-of-thumb:

1. Go to official university website.
2. If possible, switch to English language version.
3. Determine the English name from the following locations (in order of preference):
    1. website title
    2. copyright notice in footer
    2. "about" page
    2. imprint
    3. frequent occurrences in press statements
    4. (fallback) foreign language name

Here's what I came up with:
- Webis:
    - [x] Bauhaus-Universität Weimar
    - [x] Friedrich Schiller University Jena
    - [x] Leibniz University Hannover
    - [x] Leipzig University
    - [x] University of Groningen
- other:
    - Bielefeld University
    - Cornell Univeristy
    - Hofstra University
    - Ludwig-Maximilians-Universität München
    - NCSR Demokritos
    - Skolkovo Institute of Science and Technology (or Skoltech)
    - Technical University of Darmstadt
    - University of Dundee
    - University of North Carolina Greensboro
    - University of Pittsburgh
    - University of the Aegean
    - Universität Hamburg
    - Uppsala Universitet

Please comment below if you object the naming.

(Working on this in #18)

**Comment by johanneskiesel** [comment]
Seems to be done, according to the link #18
